[package]
name = "rxhtml"
version = "0.0.1"
authors = ["jxz_211 <jxz_211@163.com>"]
edition = "2018"
licence = "MIT"
description = "a html/xml parser"
repository = "https://github.com/fefit/rxhtml"

[dependencies]
lazy_static = "1.4.0"
wasm-bindgen = "0.2"

[lib]
name = "rxhtml"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false