[package]
name = "chtml"
version = "0.0.1"
authors = ["ganmin <ganmin@360.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static="1.4.0"

[lib]
name="chtml"
path="src/lib.rs"

[[bin]]
name="chtml"
path="src/main.rs"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "chtml_benchmark"
harness = false