[package]
name = "rxhtml"
version = "0.0.1"
authors = ["jxz_211 <jxz_211@163.com>"]
edition = "2018"
license = "MIT"
description = "a html/xml parser"
repository = "https://github.com/fefit/rxhtml"

[dependencies]
lazy_static = "1.4.0"
wasm-bindgen = { version="0.2.68", features = ["serde-serialize"] }
serde = { version = "1.0.116", features = ["derive", "rc"] }
serde_json = "1.0.57"


[lib]
name = "rxhtml"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
criterion = "0.3"
wasm-bindgen-test = "0.3.18"

[[bench]]
name = "benchmark"
harness = false

[[bin]]
name="rxhtml"
path="src/main.rs"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false