[package]
name = "rphtml"
version = "0.1.1"
authors = ["jxz_211 <jxz_211@163.com>"]
edition = "2018"
license = "MIT"
description = "a html parser write in rust."
repository = "https://github.com/fefit/rphtml"
keywords = ["html", "parser", "html parser", "html minify", "html render"]
categories = ["parser-implementations", "wasm"]
readme = "README.md"
license-file = "LICENSE"

[dependencies]
lazy_static = "1.4.0"
wasm-bindgen = { version="0.2.68", features = ["serde-serialize"] }
js-sys = { version = "0.3.45" }
serde = { version = "1.0.116", features = ["derive", "rc"] }
serde_json = "1.0.57"
console_error_panic_hook = "0.1.6"

[lib]
name = "rphtml"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dev-dependencies]
criterion = "0.3"
wasm-bindgen-test = "0.3.18"

[[bench]]
name = "benchmark"
harness = false

[[bin]]
name="rphtml"
path="src/main.rs"